remote_theme: sylhare/Type-on-Strap
baseurl: "/munge-js"
url: "https://icheka.github.io"
# BLOG CONFIGURATION
post_navigation: false
plugins: [jekyll-seo-tag]
title: MungeJS                 # Name of website
description: MungeJS is a flexible DSL for representing scraping logic as code that can be stored anywhere -- as text files in a file system, as JSON files in a code repository, even as textual data in a database. MungeJS separates the representation of web-scraping logic from its execution.            # Short description, primarily used by search engines
color_theme: auto                     # color theme auto, dark or light
header_text: MungeJS
footer_text: "License: MIT"